# Multi-stage build for PocketBase
FROM docker.io/golang:1.24-alpine as builder

# Set working directory
WORKDIR /spinroute

# Copy go mod files first for better caching
COPY . .
# COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
# COPY . .
# COPY ./pb_migrations ./pb_migrations
# COPY ./pb_public ./pb_public
# COPY ./pb_hooks ./pb_hooks

ENV APP_ENV=dev
ENV SPINROUTE_APP_STORE_SANDBOX=true
ENV SPINROUTE_CONSUME_WS=false
ENV SPINROUTE_VERBOSE=false
ENV SPINROUTE_BOOTSTRAP_NETWORKS=false

# Build the binary (using the command from package.json)
# RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -o ./bin/spinroute-pb ./cmd/spinroute-pb/main.go
CMD ["go", "run", "/spinroute/cmd/spinroute-pb/main.go", "serve", "--dev", "--http=0.0.0.0:8090"]

# # Final stage
# FROM alpine:latest

# # Install ca-certificates for HTTPS support
# RUN apk add --no-cache ca-certificates curl

# # Create non-root user for security
# RUN addgroup -g 1001 pocketbase && \
#     adduser -D -s /bin/sh -u 1001 -G pocketbase pocketbase

# RUN mkdir /spinroute

# # Copy PocketBase binary from builder stage
# COPY --from=builder /usr/src/spinroute/spinroute-pb /spinroute/spinroute-pb

# RUN chmod +x /spinroute/spinroute-pb

# # # Create necessary directories
# # RUN mkdir -p /spinroute/pb_data /spinroute/pb_public /spinroute/pb_migrations && \
# #     chown -R pocketbase:pocketbase /spinroute/pb_data /spinroute/pb_public /spinroute/pb_migrations

# # # Copy application files
# # COPY --chown=pocketbase:pocketbase pb_public /spinroute/pb_public
# # COPY --chown=pocketbase:pocketbase pb_migrations /spinroute/pb_migrations

# # Switch to non-root user
# USER pocketbase


# Final stage
# FROM alpine:latest

# WORKDIR /spinroute

# COPY . .

# COPY --from=builder /spinroute/bin/spinroute-pb ./spinroute-pb

# # Expose port
# EXPOSE 8090

# # Health check
# HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
#     CMD curl -f http://localhost:8090/api/health || exit 1

# ENV BOOTSTRAP_NETWORKS=false
# ENV BOOTSTRAP_COMPONENTS=false
# ENV CONSUME_WS=false
# ENV LOG_UPSERTS=false

# # Default command
# CMD ["/spinroute/spinroute-pb", "serve", "--http=0.0.0.0:8090"]
