{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}-ingress
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      {{- if .Values.backend.enabled }}
      # Backend API routes
      - path: {{ .Values.ingress.backend.path }}
        pathType: {{ .Values.ingress.backend.pathType }}
        backend:
          service:
            name: {{ .Values.backend.name }}
            port:
              number: {{ .Values.backend.service.port }}
      {{- end }}
      {{- if .Values.frontend.enabled }}
      # Frontend routes (should be last to catch all remaining paths)
      - path: {{ .Values.ingress.frontend.path }}
        pathType: {{ .Values.ingress.frontend.pathType }}
        backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              number: {{ .Values.frontend.service.port }}
      {{- end }}
{{- end }}
