FROM docker.io/oven/bun:latest AS builder

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json bun.lock ./
COPY drizzle.config.ts ./
COPY drizzle ./drizzle

# Install app dependencies
RUN bun install

RUN bunx drizzle-kit generate
# RUN bunx drizzle-kit migrate

COPY lib ./lib
COPY src ./src

FROM docker.io/oven/bun:alpine AS runner

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000
CMD [ "bunx", "drizzle-kit", "migrate", "&&", "bun", "run", "start" ]