apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices-blog
  name: api-gateway
  labels:
    app: api-gateway-backend
    service: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway-backend
      service: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway-backend
        service: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: api-gateway:latest
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi