apiVersion: v1
kind: Service
metadata:
  namespace: microservices-blog
  name: api-gateway
spec:
  selector:
    app: api-gateway-backend
    service: api-gateway
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP  # Internal service, only accessible within cluster