# Production environment values
global:
  namespace: microservices-prod
  imageTag: stable
  imagePullPolicy: IfNotPresent

# Multiple replicas for production
backend:
  replicas: 3
  env:
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "3000"
    - name: LOG_LEVEL
      value: "info"

frontend:
  replicas: 3

# Production resource allocations
microservices:
  - name: bikeshare
    enabled: true
    replicas: 2
    image:
      tag: stable
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

  - name: fleet
    enabled: true
    replicas: 2
    image:
      tag: stable
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

  - name: journey
    enabled: true
    replicas: 2
    image:
      tag: stable
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

  - name: routing
    enabled: true
    replicas: 2
    image:
      tag: stable
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

ingress:
  host: microservices.yourdomain.com
  tls:
    enabled: true
    secretName: microservices-tls
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

# Enable HPA for production
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
