# Development environment values
global:
  namespace: microservices-dev
  imageTag: dev
  imagePullPolicy: Always

# Development volume mounts
volumes:
  enabled: true
  hostPath: /host-home/Code/bun-astro-nest-microservices
  mountPath: /app

# Single replica for development
backend:
  replicas: 1
  env:
    - name: NODE_ENV
      value: "development"
    - name: PORT
      value: "3000"
    - name: LOG_LEVEL
      value: "debug"

frontend:
  replicas: 1

# Reduced resources for development
microservices:
  - name: bikeshare
    enabled: true
    replicas: 1
    port: 3000
    image:
      tag: dev
    env:
      - name: NODE_ENV
        value: "development"
      - name: PORT
        value: "3000"
      - name: SERVICE_NAME
        value: "bikeshare"
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

  - name: fleet
    enabled: true
    replicas: 1
    port: 3000
    image:
      tag: dev
    env:
      - name: NODE_ENV
        value: "development"
      - name: PORT
        value: "3000"
      - name: SERVICE_NAME
        value: "fleet"
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

  - name: journey
    enabled: true
    replicas: 1
    port: 3000
    image:
      tag: dev
    env:
      - name: NODE_ENV
        value: "development"
      - name: PORT
        value: "3000"
      - name: SERVICE_NAME
        value: "journey"
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

  - name: routing
    enabled: true
    replicas: 1
    port: 3000
    image:
      tag: dev
    env:
      - name: NODE_ENV
        value: "development"
      - name: PORT
        value: "3000"
      - name: SERVICE_NAME
        value: "routing"
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

ingress:
  host: 192.168.49.2.nip.io
  
# Disable HPA for development
hpa:
  enabled: false

# Enable database for development
database:
  enabled: true
  persistence:
    enabled: false  # Use emptyDir for development
  auth:
    database: microservices_dev
    username: postgres
    password: dev_password
